# Cloudflare Workers Configuration
name = "vlcdn"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "32f9d5fc58dd05437ec5eacae4ac3b79" # Isi dengan Account ID Cloudflare Anda
workers_dev = true

# KV Namespace untuk menyimpan akun VLESS
[[kv_namespaces]]
binding = "VLESS_ACCOUNTS"
id = "VLESS_ACCOUNTS" # Isi dengan KV Namespace ID setelah dibuat

# Environment Variables (opsional)
[vars]
ENVIRONMENT = "production"
MAX_ACCOUNTS = "100"
DEFAULT_PATH = "/ws"
DEFAULT_PORT = "443"

# Routes (jika ingin custom domain)
# [[routes]]
# pattern = "vpn.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Limits
[limits]
cpu_ms = 50

# Observability (opsional untuk debugging)
[observability]
enabled = true

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.kv_namespaces]]
binding = "VLESS_ACCOUNTS"
id = "VLESS_ACCOUNTS" # KV Namespace ID untuk development

# Production configuration
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "VLESS_ACCOUNTS"
id = "VLESS_ACCOUNTS" # KV Namespace ID untuk production

# Build configuration
[build]
command = ""
compatibility_flags = []
