# Cloudflare Workers Configuration
name = "vlcdn"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = ""
workers_dev = true

# KV Namespace untuk menyimpan akun VLESS
[[kv_namespaces]]
# Isi dengan KV Namespace ID setelah dibuat
binding = "VLESS_ACCOUNTS"
id = "45d73fbf51d24c448c5d0385b4a47316"

# Environment Variables (opsional)
[vars]
ENVIRONMENT = "production"
MAX_ACCOUNTS = "100"
DEFAULT_PATH = "/ws"
DEFAULT_PORT = "443"

# Routes (jika ingin custom domain)
# [[routes]]
# pattern = "vpn.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Observability (opsional untuk debugging)
[observability]
enabled = true

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.kv_namespaces]]
# KV Namespace ID untuk development
binding = "VLESS_ACCOUNTS"
id = "45d73fbf51d24c448c5d0385b4a47316"

# Production configuration
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
# KV Namespace ID untuk production
binding = "VLESS_ACCOUNTS"
id = "45d73fbf51d24c448c5d0385b4a47316"

# Build configuration
[build]
command = ""
